---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dayio-{{ .Values.appName }}
  namespace: {{ .Values.environment }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.url }}
    http:
      paths:
      - backend:
          service:
            name: dayio-{{ .Values.appName }}
            port: 
              number: {{ .Values.port }}
        path: /user
        pathType: ImplementationSpecific